name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: setup gcc
      run: sudo apt install build-essential
    - name: configure
      run: g++ corcheck.cpp output.cpp tetris.cpp -o tetris --static
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
       repo_token: ${{ secrets.TOKEN }}
       file: tetris
       tag: ${{ github.ref }}
       overwrite: true
