name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: configure
      run: g++ corcheck.cpp output.cpp tetris.cpp -o tetris
    - name: make
      run: ./tetris
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
